export const FETCH_LOCAL_RADIO_START = 'FETCH_LOCAL_RADIO_START';
export const FETCH_LOCAL_RADIO_SUCCESS = 'FETCH_LOCAL_RADIO_SUCCESS';
export const FETCH_LOCAL_RADIO_FAIL = 'FETCH_LOCAL_RADIO_FAIL';

export const GET_RADIO_STATION_START = 'GET_RADIO_STATION_START';
export const GET_RADIO_STATION_SUCCESS = 'GET_RADIO_STATION_SUCCESS';
export const GET_RADIO_STATION_FAIL = 'GET_RADIO_STATION_FAIL';

export const GET_RADIO_COUNTRY_LIST = 'GET_RADIO_COUNTRY_LIST';
export const GET_RADIO_COUNTRY_SUCCESS = 'GET_RADIO_COUNTRY_SUCCESS';
export const GET_RADIO_COUNTRY_FAIL = 'GET_RADIO_COUNTRY_FAIL';
